# Generated by Django 3.2.2 on 2021-07-15 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_rename_post_post_porofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='porofile',
            new_name='profile',
        ),
    ]
