# Generated by Django 3.2.2 on 2021-07-20 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_post_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_picture',
            field=models.ImageField(null=True, upload_to='posts/photos'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
