# Generated by Django 3.2.2 on 2021-07-17 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='static/images/default-profile.png', null=True, upload_to='users/pictures'),
        ),
    ]
